"""initial schema

Revision ID: e4211f35a275
Revises: 
Create Date: 2026-06-07 20:21:31.153207
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e4211f35a275'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athletes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('prenom', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('club', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom', 'prenom', 'birth_date', name='uq_athlete_identity')
    )
    with op.batch_alter_table('athletes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_athletes_nom'), ['nom'], unique=False)

    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('is_relay', sa.Boolean(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'event_date', 'event_type', name='uq_course_identity')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_name'), ['name'], unique=False)

    op.create_table('pending_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('provider_hint', sa.String(), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.Column('handled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('club', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('bib_number', sa.String(), nullable=True),
    sa.Column('rank_overall', sa.Integer(), nullable=True),
    sa.Column('rank_category', sa.Integer(), nullable=True),
    sa.Column('rank_gender', sa.Integer(), nullable=True),
    sa.Column('total_time', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('splits', sa.JSON(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'bib_number', name='uq_participation_bib')
    )
    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participations_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_participations_course_id'), ['course_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participations_course_id'))
        batch_op.drop_index(batch_op.f('ix_participations_athlete_id'))

    op.drop_table('participations')
    op.drop_table('pending_providers')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_name'))
        batch_op.drop_index(batch_op.f('ix_courses_event_type'))

    op.drop_table('courses')
    with op.batch_alter_table('athletes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_athletes_nom'))

    op.drop_table('athletes')
    # ### end Alembic commands ###
